// <auto-generated />
using System;
using EventScheduler.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventScheduler.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250222182138_changeColumn2")]
    partial class changeColumn2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("EventScheduler.Models.Event", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("_title")
                        .HasColumnType("TEXT");

                    b.HasKey("_id");

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
